### ISSUE TITLE
Fallo al comprobar dispositivo Rooteado (Movil-Huawei PSmart

### ISSUE THREAD

**Issue by CristobalMancera98** [Quantika14/guasap-whatsapp-foresincs-tool#11]
![no rootea](https://user-images.githubusercontent.com/47178395/51979480-890f9800-248d-11e9-8370-84b693bd90b9.png)
Nos informa que esta rooteado y nos abre las opciones para dispositivos rooteado pero sin embargo el dispositivo no se encuentra rooteado, sin embargo en el terminal nos indica que no esta rooteado.

**Comment by Quantika14** [comment]
Hola Cristobal, muchas gracias por tu mensajes.
Guasap Forensic realiza varias pruebas para identificar si ahora es ROOT y si con anterioridad también lo estuvo. Es decir, no solo concluye el presente, sino también el pasado.
Para ello, busca los permisos de las aplicaciones y apk almacenados. También realiza otras comprobaciones. ¿Es posible que el dispositivo haya sido rooteado con anterioridad?
Añadimos a la lista cambiar la imagen para causar menos confusión.
Un cordial saludo.

**Comment by CristobalMancera98** [comment]
Buenas, el dispositivo no ha sido anteriormente rooteado debido a que es nuevo.
