### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by thehappydinoa** [Quantika14/guasap-whatsapp-foresincs-tool#9]
Why not just use Magisk which works for everything 5+?

**Comment by Quantika14** [comment]
Hi, tanks for your question. Interesting question. We will study how to identify root with Magisk. 

You know some file to identify that magisk is installed?
Thank you. Regards.

**Comment by thehappydinoa** [comment]
I believe the file `/data/adb/magisk_debug.log` is automatically created.

**Comment by JWScr33d** [comment]
Perfect, i'm going to create a new functionality that checks if that file exists. Thank you very much.

**Comment by thehappydinoa** [comment]
Ya, also Magisk can root universally. [XDA Forum](https://forum.xda-developers.com/apps/magisk/official-magisk-v7-universal-systemless-t3473445)
